"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vkz_nc7px79%*sllh5bhtxpjinrf6w4s*&965d1lk)&x)^c3%n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {

    # =================================
    # BRANDING
    # =================================
    "site_title": "Blogy Admin",
    "site_header": "Blogy Management",
    "site_brand": "Blogy",

    "welcome_sign": "Selamat Datang di Dashboard Blogy",
    "copyright": "Blogy",

    # =================================
    # LOGO
    # =================================
    "site_logo": "assets/img/logoblogy.png",
    "login_logo": "assets/img/logoblogy2.png",

    # =================================
    # SEARCH
    # =================================
    "search_model": [
        "blog.Post",
        "blog.Category",
        "auth.User",
    ],

    # =================================
    # SIDEBAR
    # =================================
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # =================================
    # ORDER MENU
    # =================================
    "order_with_respect_to": [
        "blog",
        "auth",
    ],

    # =================================
    # ICONS
    # =================================
    "icons": {

        # Blog
        "blog.Post": "fas fa-newspaper",
        "blog.Category": "fas fa-folder-open",
        "blog.Tag": "fas fa-tags",
        "blog.Comment": "fas fa-comments",

        # User
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

    },

    # =================================
    # TOP MENU
    # =================================
    "topmenu_links": [

        {
            "name": "Website",
            "url": "/",
            "new_window": True
        },

        {
            "model": "blog.Post"
        },

        {
            "app": "blog"
        },
    ],

    # =================================
    # UI
    # =================================
    "show_ui_builder": False,

    # =================================
    # USER MENU
    # =================================
    "usermenu_links": [
        {
            "name": "Lihat Website",
            "url": "/",
            "new_window": True
        },
    ],

}

JAZZMIN_UI_TWEAKS = {

    # Tema terang
    "theme": "flatly",

    # Dark mode
    "dark_mode_theme": "darkly",

    # Navbar
    "navbar": "navbar-white navbar-light",

    # Sidebar
    "sidebar": "sidebar-light-primary",

    # Brand
    "brand_colour": "navbar-primary",

    # Accent
    "accent": "accent-primary",

    # Sidebar style
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,

    # Buttons
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}